## Merge- GLD & FSM

In [1]:
#import libraries
import pandas as pd

#load dataset
gld = pd.read_csv('../data_clean/gld_clean.csv')
fsm = pd.read_csv('../data_clean/fsm_clean.csv')

In [5]:
#data validation
gld.head()

     la_code                 borough   gld
0  E09000007                  Camden  68.3
1  E09000001          City of London  84.2
2  E09000012                 Hackney  69.5
3  E09000013  Hammersmith and Fulham  66.9
4  E09000014                Haringey  73.2

In [6]:
#data validation
fsm.head()

     la_code               borough    fsm
0  E09000002  Barking and Dagenham  31.20
1  E09000003                Barnet  24.46
2  E09000004                Bexley  22.76
3  E09000005                 Brent  24.31
4  E09000006               Bromley  18.29

In [7]:
#merge
df_merged = pd.merge(gld, fsm, on='la_code', how='inner')

In [12]:
#validate merge
print("Merged rows:", len(df_merged))

Merged rows: 33

In [13]:
#validation of borough names
print("Borough match check:",
      (df_merged['borough_x'] == df_merged['borough_y']).all())

print(df_merged.head())

Borough match check: True
     la_code               borough_x   gld               borough_y    fsm
0  E09000007                  Camden  68.3                  Camden  46.67
1  E09000001          City of London  84.2          City of London  21.93
2  E09000012                 Hackney  69.5                 Hackney  44.66
3  E09000013  Hammersmith and Fulham  66.9  Hammersmith and Fulham  34.50
4  E09000014                Haringey  73.2                Haringey  31.09

In [14]:
#clean duplicate columns
df_merged = df_merged.drop(columns=['borough_y'])
df_merged = df_merged.rename(columns={'borough_x': 'borough'})

In [15]:
#final structure check
print(df_merged.head())

     la_code                 borough   gld    fsm
0  E09000007                  Camden  68.3  46.67
1  E09000001          City of London  84.2  21.93
2  E09000012                 Hackney  69.5  44.66
3  E09000013  Hammersmith and Fulham  66.9  34.50
4  E09000014                Haringey  73.2  31.09

In [16]:
#save merged data
df_merged.to_csv('../data_clean/gld_fsm_merged.csv', index=False)

In [17]:
#Quick analysis
print("Correlation:")
print(df_merged[['gld', 'fsm']].corr())

Correlation:
          gld       fsm
gld  1.000000 -0.393048
fsm -0.393048  1.000000

## Merge SEN to master dataset

In [18]:
#load dataset
sen = pd.read_csv('../data_clean/sen_clean.csv')

In [19]:
#merge
df_merged = pd.merge(df_merged, sen, on='la_code', how='inner')

In [20]:
#validate
print("Rows after SEN merge:", len(df_merged))
df_merged.head()

Rows after SEN merge: 33

,la_code,borough_x,gld,fsm,borough_y,sen
0,E09000007,Camden,68.3,46.67,Camden,17.681992
1,E09000001,City of London,84.2,21.93,City of London,11.488783
2,E09000012,Hackney,69.5,44.66,Hackney,19.183618
3,E09000013,Hammersmith and Fulham,66.9,34.50,Hammersmith and Fulham,17.610787
4,E09000014,Haringey,73.2,31.09,Haringey,17.629577

In [21]:
#clean duplicate columns
df_merged = df_merged.drop(columns=['borough_y'])
df_merged = df_merged.rename(columns={'borough_x': 'borough'})

In [23]:
#save merged
df_merged.to_csv('../data_clean/gld_fsm_sen_merged.csv', index=False)

In [26]:
#validate
df_merged.head()

      la_code               borough   gld    fsm        sen
1   E09000001        City of London  84.2  21.93  11.488783
30  E09000027  Richmond upon Thames  75.6  15.06  14.218513
32  E09000031        Waltham Forest  74.4  28.91  16.623858
4   E09000014              Haringey  73.2  31.09  17.629577
18  E09000006               Bromley  72.3  18.29  17.209875

In [27]:
#top 5 boroughs by GLD
df_merged.sort_values(by='gld', ascending=False).head()

      la_code               borough   gld    fsm        sen
1   E09000001        City of London  84.2  21.93  11.488783
30  E09000027  Richmond upon Thames  75.6  15.06  14.218513
32  E09000031        Waltham Forest  74.4  28.91  16.623858
4   E09000014              Haringey  73.2  31.09  17.629577
18  E09000006               Bromley  72.3  18.29  17.209875

In [28]:
#lowest 5 boroughs by GLD
df_merged.sort_values(by='gld', ascending=True).head()

      la_code               borough   gld    fsm        sen
24  E09000016              Havering  64.8  21.71  12.526500
21  E09000010               Enfield  65.2  33.50  16.397957
14  E09000002  Barking and Dagenham  65.2  31.20  15.734863
11  E09000030         Tower Hamlets  65.2  46.45  18.333231
13  E09000033           Westminster  65.7  42.68  17.812510

In [29]:
#Top 5 by FSM
df_merged.sort_values(by='fsm', ascending=False).head()

      la_code        borough   gld    fsm        sen
5   E09000019      Islington  66.6  49.69  22.219987
0   E09000007         Camden  68.3  46.67  17.681992
11  E09000030  Tower Hamlets  65.2  46.45  18.333231
2   E09000012        Hackney  69.5  44.66  19.183618
13  E09000033    Westminster  65.7  42.68  17.812510

In [30]:
#top 5 by SEN
df_merged.sort_values(by='sen', ascending=False).head()

      la_code     borough   gld    fsm        sen
5   E09000019   Islington  66.6  49.69  22.219987
22  E09000011   Greenwich  70.1  33.09  19.815498
8   E09000023    Lewisham  69.7  31.88  19.754279
12  E09000032  Wandsworth  71.9  32.10  19.733438
7   E09000022     Lambeth  67.2  42.63  19.639905

In [25]:
#correlation
df_merged.corr(numeric_only=True)

          gld       fsm       sen
gld  1.000000 -0.393048 -0.312377
fsm -0.393048  1.000000  0.671496
sen -0.312377  0.671496  1.000000