## Merge- GLD & FSM

In [1]:
#import libraries
import pandas as pd

#load dataset
gld = pd.read_csv('../data_clean/gld_clean.csv')
fsm = pd.read_csv('../data_clean/fsm_clean.csv')

In [2]:
#data validation
gld.head()

     la_code                 borough   gld
0  E09000007                  Camden  68.3
1  E09000012                 Hackney  69.5
2  E09000013  Hammersmith and Fulham  66.9
3  E09000014                Haringey  73.2
4  E09000019               Islington  66.6

In [3]:
#data validation
fsm.head()

     la_code               borough    fsm
0  E09000002  Barking and Dagenham  31.20
1  E09000003                Barnet  24.46
2  E09000004                Bexley  22.76
3  E09000005                 Brent  24.31
4  E09000006               Bromley  18.29

In [4]:
#merge
df_merged = pd.merge(gld, fsm, on='la_code', how='inner')

In [5]:
#validate merge
print("Merged rows:", len(df_merged))

Merged rows: 32

In [6]:
#validation of borough names
print("Borough match check:",
      (df_merged['borough_x'] == df_merged['borough_y']).all())

print(df_merged.head())

Borough match check: True
     la_code               borough_x   gld               borough_y    fsm
0  E09000007                  Camden  68.3                  Camden  46.67
1  E09000012                 Hackney  69.5                 Hackney  44.66
2  E09000013  Hammersmith and Fulham  66.9  Hammersmith and Fulham  34.50
3  E09000014                Haringey  73.2                Haringey  31.09
4  E09000019               Islington  66.6               Islington  49.69

In [7]:
#clean duplicate columns
df_merged = df_merged.drop(columns=['borough_y'])
df_merged = df_merged.rename(columns={'borough_x': 'borough'})

In [8]:
#final structure check
print(df_merged.head())

     la_code                 borough   gld    fsm
0  E09000007                  Camden  68.3  46.67
1  E09000012                 Hackney  69.5  44.66
2  E09000013  Hammersmith and Fulham  66.9  34.50
3  E09000014                Haringey  73.2  31.09
4  E09000019               Islington  66.6  49.69

In [9]:
#save merged data
df_merged.to_csv('../data_clean/gld_fsm_merged.csv', index=False)

## Merge SEN to master dataset

In [10]:
#load dataset
sen = pd.read_csv('../data_clean/sen_clean.csv')

In [11]:
#merge
df_merged = pd.merge(df_merged, sen, on='la_code', how='inner')

In [12]:
#validate
print("Rows after SEN merge:", len(df_merged))
df_merged.head()

Rows after SEN merge: 32

,la_code,borough_x,gld,fsm,borough_y,sen
0,E09000007,Camden,68.3,46.67,Camden,17.681992
1,E09000012,Hackney,69.5,44.66,Hackney,19.183618
2,E09000013,Hammersmith and Fulham,66.9,34.50,Hammersmith and Fulham,17.610787
3,E09000014,Haringey,73.2,31.09,Haringey,17.629577
4,E09000019,Islington,66.6,49.69,Islington,22.219987

In [13]:
#clean duplicate columns
df_merged = df_merged.drop(columns=['borough_y'])
df_merged = df_merged.rename(columns={'borough_x': 'borough'})

In [14]:
#save merged
df_merged.to_csv('../data_clean/gld_fsm_sen_merged.csv', index=False)

In [15]:
#validate
df_merged.head()

     la_code                 borough   gld    fsm        sen
0  E09000007                  Camden  68.3  46.67  17.681992
1  E09000012                 Hackney  69.5  44.66  19.183618
2  E09000013  Hammersmith and Fulham  66.9  34.50  17.610787
3  E09000014                Haringey  73.2  31.09  17.629577
4  E09000019               Islington  66.6  49.69  22.219987

In [16]:
#top 5 boroughs by GLD
df_merged.sort_values(by='gld', ascending=False).head()

      la_code               borough   gld    fsm        sen
29  E09000027  Richmond upon Thames  75.6  15.06  14.218513
31  E09000031        Waltham Forest  74.4  28.91  16.623858
3   E09000014              Haringey  73.2  31.09  17.629577
17  E09000006               Bromley  72.3  18.29  17.209875
26  E09000021  Kingston upon Thames  72.1  16.41  15.571846

In [17]:
#lowest 5 boroughs by GLD
df_merged.sort_values(by='gld', ascending=True).head()

      la_code               borough   gld    fsm        sen
23  E09000016              Havering  64.8  21.71  12.526500
20  E09000010               Enfield  65.2  33.50  16.397957
10  E09000030         Tower Hamlets  65.2  46.45  18.333231
13  E09000002  Barking and Dagenham  65.2  31.20  15.734863
12  E09000033           Westminster  65.7  42.68  17.812510

In [18]:
#Top 5 by FSM
df_merged.sort_values(by='fsm', ascending=False).head()

      la_code        borough   gld    fsm        sen
4   E09000019      Islington  66.6  49.69  22.219987
0   E09000007         Camden  68.3  46.67  17.681992
10  E09000030  Tower Hamlets  65.2  46.45  18.333231
1   E09000012        Hackney  69.5  44.66  19.183618
12  E09000033    Westminster  65.7  42.68  17.812510

In [19]:
#top 5 by SEN
df_merged.sort_values(by='sen', ascending=False).head()

      la_code     borough   gld    fsm        sen
4   E09000019   Islington  66.6  49.69  22.219987
21  E09000011   Greenwich  70.1  33.09  19.815498
7   E09000023    Lewisham  69.7  31.88  19.754279
11  E09000032  Wandsworth  71.9  32.10  19.733438
6   E09000022     Lambeth  67.2  42.63  19.639905

In [20]:
#correlation
df_merged.corr(numeric_only=True)

          gld       fsm       sen
gld  1.000000 -0.395175 -0.078935
fsm -0.395175  1.000000  0.667018
sen -0.078935  0.667018  1.000000

## Merge IDACI to master dataset

In [21]:
#load IDACI cleaned dataset
idaci = pd.read_csv('../data_clean/idaci_clean.csv')

In [22]:
#merge to master dataset
df_merged = pd.merge(df_merged, idaci, on='la_code', how='inner')

In [23]:
#Validate
print(len(df_merged))

32

In [24]:
#validate
df_merged.head()

,la_code,borough_x,gld,fsm,sen,borough_y,idaci
0,E09000007,Camden,68.3,46.67,17.681992,Camden,0.182241
1,E09000012,Hackney,69.5,44.66,19.183618,Hackney,0.255382
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,Hammersmith and Fulham,0.181938
3,E09000014,Haringey,73.2,31.09,17.629577,Haringey,0.201324
4,E09000019,Islington,66.6,49.69,22.219987,Islington,0.268195

In [25]:
#drop duplicate borough column
df_merged = df_merged.drop(columns=['borough_y'])

In [26]:
#rename remaining column
df_merged = df_merged.rename(columns={'borough_x': 'borough'})

In [27]:
#reconfirm duplicate column does not exist
df_merged.head()

     la_code                 borough   gld    fsm        sen     idaci
0  E09000007                  Camden  68.3  46.67  17.681992  0.182241
1  E09000012                 Hackney  69.5  44.66  19.183618  0.255382
2  E09000013  Hammersmith and Fulham  66.9  34.50  17.610787  0.181938
3  E09000014                Haringey  73.2  31.09  17.629577  0.201324
4  E09000019               Islington  66.6  49.69  22.219987  0.268195

In [28]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge OFSTED RATINGS to master dataset

In [29]:
#Load OFSTED dataset
ofsted = pd.read_csv('../data_clean/ofsted_clean.csv')

In [30]:
#merge to master dataset
df_merged = pd.merge(df_merged, ofsted, on='borough', how='inner')

In [31]:
#validate
len(df_merged)

32

In [32]:
#reconfirm
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183

In [33]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge OFSTED places to master dataset

In [34]:
#Load OFSTED places dataset
ofsted_places = pd.read_csv('../data_clean/ofsted_places.csv')

In [35]:
#merge to master dataset
df_merged = pd.merge(df_merged, ofsted_places, on='borough', how='inner')

In [36]:
#validate
len(df_merged)

32

In [37]:
#reconfirm
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208

In [38]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge ONS_under5 population to master dataset

In [39]:
#Load Under5 pop places dataset
ons = pd.read_csv('../data_clean/ons_under5.csv')

In [40]:
#select needed column
ons = ons[['borough', 'under5']]

In [41]:
#merge to master dataset
df_merged = pd.merge(df_merged, ons, on='borough', how='inner')

In [42]:
#validate
len(df_merged)

32

In [43]:
#reconfirm
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places,under5
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037,9934
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233,16247
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619,9237
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700,14962
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208,10798

In [44]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge childcare access to master dataset

In [45]:
#Load childcare access dataset
childcare = pd.read_csv('../data_clean/childcare_access.csv')

In [46]:
#merge to master dataset
df_merged = pd.merge(df_merged, childcare, on='borough', how='inner')

In [47]:
#validate
len(df_merged)

32

In [48]:
#reconfirm
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places,under5,childcare_per_100
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037,9934,50.704651
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233,16247,50.673971
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619,9237,50.005413
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700,14962,38.096511
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208,10798,48.231154

In [49]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge ethnic diversity to master dataset

In [50]:
#Load ethnic diversity dataset
ethnic_diversity = pd.read_csv('../data_clean/ethnic_diversity.csv')

In [51]:
#merge to master dataset
df_merged = pd.merge(df_merged, ethnic_diversity, on='borough', how='inner')

In [52]:
#validate
len(df_merged)

32

In [53]:
#reconfirm
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places,under5,childcare_per_100,ethnic_diversity
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037,9934,50.704651,0.812638
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233,16247,50.673971,0.828401
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619,9237,50.005413,0.793292
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700,14962,38.096511,0.825132
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208,10798,48.231154,0.790226

In [54]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)

## Merge house prices to master dataset

In [55]:
#Load house prices dataset
house_prices = pd.read_csv('../data_clean/house_prices_clean.csv')

In [56]:
#merge to master dataset
df_merged = pd.merge(df_merged, house_prices, on='borough', how='inner')

In [57]:
#validate
len(df_merged)

32

In [58]:
#reconfirm
df_merged.head()

,la_code_x,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places,under5,childcare_per_100,ethnic_diversity,la_code_y,average_house_price
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037,9934,50.704651,0.812638,E09000007,863493
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233,16247,50.673971,0.828401,E09000012,618385
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619,9237,50.005413,0.793292,E09000013,790884
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700,14962,38.096511,0.825132,E09000014,635522
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208,10798,48.231154,0.790226,E09000019,700374

In [59]:
#drop duplicate borough column
df_merged = df_merged.drop(columns=['la_code_y'])

In [60]:
#rename remaining column
df_merged = df_merged.rename(columns={'la_code_x': 'la_code'})

In [61]:
#reconfirm duplicate column does not exist
df_merged.head()

,la_code,borough,gld,fsm,sen,idaci,ofsted,inspection_coverage,total_places,under5,childcare_per_100,ethnic_diversity,average_house_price
0,E09000007,Camden,68.3,46.67,17.681992,0.182241,3.148813,0.652372,5037,9934,50.704651,0.812638,863493
1,E09000012,Hackney,69.5,44.66,19.183618,0.255382,3.137548,0.666707,8233,16247,50.673971,0.828401,618385
2,E09000013,Hammersmith and Fulham,66.9,34.50,17.610787,0.181938,3.173140,0.657718,4619,9237,50.005413,0.793292,790884
3,E09000014,Haringey,73.2,31.09,17.629577,0.201324,3.006351,0.773509,5700,14962,38.096511,0.825132,635522
4,E09000019,Islington,66.6,49.69,22.219987,0.268195,3.208246,0.731183,5208,10798,48.231154,0.790226,700374

In [62]:
#save master dataset
df_merged.to_csv('../data_clean/master_dataset.csv', index=False)